Repository morgan-stanley-team-3/FoodToGive, pull requests merged in 2024-08, with the labels that each got.

#2 Katy
  app/components/Header.tsx
  app/mission/page.tsx
  app/page.tsx
  app/values/page.tsx
  app/what-we-do/page.tsx
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: enhancement

#3 Frontend for Donation Form
  app/donate/page.tsx
  app/globals.css
  components.json
  components/ui/button.tsx
  components/ui/dropdown-menu.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/radio-group.tsx
  components/ui/select.tsx
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement

#1 Implement Login and Sign Up Page for Application
  actions/signup.ts
  app/api/auth/[...nextauth]/route.ts
  app/donate/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/mission/page.tsx
  app/page.tsx
  app/provider.tsx
  app/signup/page.tsx
  app/values/page.tsx
  app/what-we-do/page.tsx
  components/Header.tsx
  components/ui/card.tsx
  components/ui/checkbox.tsx
  components/ui/tabs.tsx
  lib/auth.ts
  lib/login/constants.ts
  lib/mongodb.ts
  models/User.ts
  package.json
  pnpm-lock.yaml
  postcss.config.js
  tailwind.config.js
  tailwind.config.ts
  types/next-auth.d.ts
Labels: enhancement

#12 Implement Request Page
  app/request/page.tsx
Labels: enhancement

#10 updated backend and frontend of donation form
  app/api/donation/route.ts
  app/components/Header.tsx
  app/components/PostLoginNavbar.tsx
  app/donate/page.tsx
  app/globals.css
  components/ui/carousel.tsx
  components/ui/menubar.tsx
  lib/auth.ts
  package-lock.json
  package.json
  public/foodbanklogo.webp
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#16 Add Packages to Fix Issue With Deployment
  package.json
  pnpm-lock.yaml
Labels: bug

#19 Admin and donor dashboard
  app/adminDashboard/MatchCard.tsx
  app/adminDashboard/Modal.css
  app/adminDashboard/Modal.tsx
  app/adminDashboard/Table.tsx
  app/adminDashboard/beneficiariesRequest.js
  app/adminDashboard/donnorOffer.js
  app/adminDashboard/matches.js
  app/adminDashboard/page.tsx
  app/api/donations/route.tsx
  app/components/Header.tsx
  app/donorDashboard/DonationCard.tsx
  app/donorDashboard/DonationDashboardClient.tsx
  app/donorDashboard/donnorOffer.js
  app/donorDashboard/page.tsx
  app/globals.css
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/images/images.jpeg
Labels: enhancement

#15 added chatbot
  app/api/chatbot/knowledge_base.txt
  app/api/chatbot/route.ts
  app/chatbot/page.tsx
  components/Chatbot.tsx
  components/Header.tsx
  components/ui/text-area.tsx
Labels: enhancement

#26 Add Missing Dependencies
  components/Chatbot.tsx
  components/Header.tsx
  package.json
  pnpm-lock.yaml
Labels: bug

#25 modifications to donate page
  app/api/matches/route.ts
  app/donate/page.tsx
  app/globals.css
  components/ui/command.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: bug, enhancement

#31 Implement SNS Feature
  app/adminDashboard/page.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement
